AWSTemplateFormatVersion: '2010-09-09'
Description: "Lambda function to update Pluto with published information from CAPI"
Parameters:
  CapiStreamArn:
    Type: String
    Description: Arn of the Crier kinesis stream to attach to
  DestinationStreamName:
    Type: String
    Description: Name, not ARN, of a Kinesis string to forward on to
  DestinationTopicArn:
    Type: String
    Description: ARN of an SNS topic to forward on to
  CrossAccountRoleArn:
    Type: String
    Description: ARN of a cross-account role to assume when posting messages out
  App:
    Type: String
    Description: Application identifier for RiffRaff
    Default: atom-event-forwarder
  Stack:
    Type: String
    Description: Stack identifier for RiffRaff
    Default: content-api
  Stage:
    Type: String
    AllowedValues:
      - CODE
      - DEV
      - PROD
    Description: Deployment stage
Resources:
  LambdaSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:  Launch Detector lambda function security group
      VpcId: !Ref VPCID
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: LambdaLogAccess
          PolicyDocument:
              Version: 2012-10-17
              Statement:
                Effect: Allow
                Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                Resource: "*"
        - PolicyName: LambdaVPCAccess
          PolicyDocument:
              Version: 2012-10-17
              Statement:
                Effect: Allow
                Action:
                - ec2:CreateNetworkInterface
                - ec2:DescribeNetworkInterfaces
                - ec2:DeleteNetworkInterface
                Resource: "*"
        - PolicyName: LambdaDLQAccess
          PolicyDocument:
              Version: 2012-10-17
              Statement:
                Effect: Allow
                Action:
                - sqs:SendMessage
                - sqs:SendMessageBatch
                Resource: !GetAtt DeadLetterQueue.Arn
        - PolicyName: KinesisAccess
          PolicyDocument:
              Version: 2012-10-17
              Statement:
                Effect: Allow
                Action:
                - kinesis:GetRecords
                - kinesis:GetShardIterator
                - kinesis:DescribeStream
                - kinesis:ListStreams
                Resource: !Ref CapiStreamArn
  DeadLetterQueue:
    Type: AWS::SQS::Queue
  LaunchDetectorLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: gnm-multimedia-rr-deployables
        S3Key: !Sub ${Stack}/${Stage}/${App}/launchdetector_lambda.jar
      Description: Launch Detector which updates Pluto with fresh information from Capi
      FunctionName: !Sub launchdetector-${Stage}
      Handler: AtomForwarderLambda
      Role: !Sub ${LambdaRole.Arn}
      Runtime: java8
      Timeout: 60
#      DeadLetterConfig:
#        TargetArn: !GetAtt DeadLetterQueue.Arn
      Environment:
        Variables:
          CRIER_STREAM: !Ref CapiStreamArn
          DESTINATION_STREAM_NAME: !Ref DestinationStreamName
          DESTINATION_TOPIC_ARN: !Ref DestinationTopicArn
          CROSS_ACCOUNT_ROLE_ARN: !Ref CrossAccountRoleArn
      VpcConfig:
        SecurityGroupIds:
          - !Ref LambdaSG
        SubnetIds: !Ref DeploySubnets
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: kinesis.amazonaws.com
      SourceArn: !Ref CapiStreamArn
      FunctionName: !Sub ${LaunchDetectorLambda.Arn}